/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.41
 * Generated at: 2021-02-25 03:36:39 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import ma.youcode.doctor.entity.Date;
import ma.youcode.doctor.dao.impl.DateDaoImpl;
import org.hibernate.query.sqm.tree.expression.SqmRestrictedSubQueryExpression;
import java.util.List;
import ma.youcode.doctor.dao.impl.CommentDaoImpl;
import ma.youcode.doctor.entity.Comment;

public final class index_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("jar:file:/C:/Users/Sofia/Desktop/Doctor/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/Doctor/WEB-INF/lib/jstl-1.2.jar!/META-INF/c-1_0.tld", Long.valueOf(1153410282000L));
    _jspx_dependants.put("/WEB-INF/lib/jstl-1.2.jar", Long.valueOf(1613613029700L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("ma.youcode.doctor.dao.impl.DateDaoImpl");
    _jspx_imports_classes.add("java.util.List");
    _jspx_imports_classes.add("ma.youcode.doctor.dao.impl.CommentDaoImpl");
    _jspx_imports_classes.add("ma.youcode.doctor.entity.Date");
    _jspx_imports_classes.add("org.hibernate.query.sqm.tree.expression.SqmRestrictedSubQueryExpression");
    _jspx_imports_classes.add("ma.youcode.doctor.entity.Comment");
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fif_0026_005ftest;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fout_0026_005fvalue_005fnobody;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fc_005fif_0026_005ftest = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fc_005fout_0026_005fvalue_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.release();
    _005fjspx_005ftagPool_005fc_005fout_0026_005fvalue_005fnobody.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("   <title>Doctor</title>\r\n");
      out.write("   <meta charset=\"UTF-8\">\r\n");
      out.write("   <meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\r\n");
      out.write("   <link rel=\"stylesheet\" href=\"https://www.w3schools.com/w3css/4/w3.css\">\r\n");
      out.write("   <link rel=\"stylesheet\" href=\"https://fonts.googleapis.com/css?family=Montserrat\">\r\n");
      out.write("   <link rel=\"stylesheet\" href=\"https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css\">\r\n");
      out.write("   <link rel=\"stylesheet\" href=\"./css/home.css\">\r\n");
      out.write("   <body class=\"w3-black\">\r\n");
      out.write("      <!-- Icon Bar (Sidebar - hidden on small screens) -->\r\n");
      out.write("      <nav class=\"w3-sidebar w3-bar-block w3-small w3-hide-small w3-center\">\r\n");
      out.write("         <a href=\"#\" class=\"w3-bar-item w3-button w3-padding-large w3-black\">\r\n");
      out.write("            <i class=\"fa fa-home w3-xxlarge\"></i>\r\n");
      out.write("            <p>HOME</p>\r\n");
      out.write("         </a>\r\n");
      out.write("         <a href=\"#about\" class=\"w3-bar-item w3-button w3-padding-large w3-hover-black\">\r\n");
      out.write("            <i class=\"fa fa-user w3-xxlarge\"></i>\r\n");
      out.write("            <p>ABOUT</p>\r\n");
      out.write("         </a>\r\n");
      out.write("         <a href=\"#login-signup-section\" class=\"w3-bar-item w3-button w3-padding-large w3-hover-black\">\r\n");
      out.write("            <i class=\"fa fa-sign-in w3-xxlarge\"></i>\r\n");
      out.write("            <p>Signup & Login</p>\r\n");
      out.write("         </a>\r\n");
      out.write("         <a href=\"#q-a-page\" class=\"w3-bar-item w3-button w3-padding-large w3-hover-black\">\r\n");
      out.write("            <i class=\"fa fa-eye w3-xxlarge\"></i>\r\n");
      out.write("            <p>Q/A Page</p>\r\n");
      out.write("         </a>\r\n");
      out.write("         <a href=\"#ask-for-appointment\" class=\"w3-bar-item w3-button w3-padding-large w3-hover-black\">\r\n");
      out.write("            <i class=\"fa fa-envelope w3-xxlarge\"></i>\r\n");
      out.write("            <p>Ask for appointment</p>\r\n");
      out.write("         </a>\r\n");
      out.write("      </nav>\r\n");
      out.write("      <!-- Navbar on small screens (Hidden on medium and large screens) -->\r\n");
      out.write("      <div class=\"w3-top w3-hide-large w3-hide-medium\" id=\"myNavbar\">\r\n");
      out.write("         <div class=\"w3-bar w3-black w3-opacity w3-hover-opacity-off w3-center w3-small\">\r\n");
      out.write("            <a href=\"#\" class=\"w3-bar-item w3-button\" style=\"width:25% !important\">HOME</a>\r\n");
      out.write("            <a href=\"#about\" class=\"w3-bar-item w3-button\" style=\"width:20% !important\">ABOUT</a>\r\n");
      out.write("            <a href=\"#login-signup-section\" class=\"w3-bar-item w3-button\" style=\"width:20% !important\">Signup & Login</a>\r\n");
      out.write("            <a href=\"#q-a-page\" class=\"w3-bar-item w3-button\" style=\"width:20% !important\">Q/A Page</a>\r\n");
      out.write("            <a href=\"#ask-for-appointment\" class=\"w3-bar-item w3-button\" style=\"width:20% !important\">Appointment</a>\r\n");
      out.write("         </div>\r\n");
      out.write("      </div>\r\n");
      out.write("      <!-- Page Content -->\r\n");
      out.write("      <div class=\"w3-padding-large\" id=\"main\">\r\n");
      out.write("      <!-- Header/Home -->\r\n");
      out.write("      <header class=\"w3-container w3-padding-32 w3-center w3-black\" id=\"home\">\r\n");
      out.write("         <h1 class=\"w3-jumbo\"><span class=\"w3-hide-small\">I'm</span> Sofia Tancredy.</h1>\r\n");
      out.write("         <p>Doctor and Neurologist.</p>\r\n");
      out.write("         <img src=\"./img/soc.jpg\" alt=\"boy\" class=\"w3-image\" width=\"992\" height=\"1108\">\r\n");
      out.write("      </header>\r\n");
      out.write("      <div class=\" w3-button w3-white w3-padding-large\" style=\"position: absolute;right:0;top:0;\">\r\n");
      out.write("         <a href=\"");
      out.print(request.getContextPath() + "/logout");
      out.write("\" class=\"w3-button\">Logout</a>\r\n");
      out.write("      </div>\r\n");
      out.write("      <!-- About Section -->\r\n");
      out.write("      <div class=\"w3-content w3-justify w3-text-grey w3-padding-64\" id=\"about\">\r\n");
      out.write("         <h2 class=\"w3-text-light-grey\">Sofia Tancredy</h2>\r\n");
      out.write("         <hr style=\"width:200px\" class=\"w3-opacity\">\r\n");
      out.write("         <p>\r\n");
      out.write("            Hello, My name is sofia and i am neurologist, which mean i usually treats disorders that affect the brain, \r\n");
      out.write("            spinal cord, and nerves, such as :\r\n");
      out.write("         <p>- Cerebrovascular disease, such as stroke\r\n");
      out.write("         <p>\r\n");
      out.write("         <p>- Demyelinating diseases of the central nervous system, such as multiple sclerosis\r\n");
      out.write("         <p>\r\n");
      out.write("         <p>- Headache disorders\r\n");
      out.write("         <p>\r\n");
      out.write("         <p>-Infections of the brain and peripheral nervous system\r\n");
      out.write("         <p>\r\n");
      out.write("         </p>\r\n");
      out.write("      </div>\r\n");
      out.write("      <!-- Signup & Login Section -->\r\n");
      out.write("      <div class=\"w3-content w3-justify w3-text-grey w3-padding-64\" id=\"login-signup-section\">\r\n");
      out.write("         <!-- Grid for pricing tables -->\r\n");
      out.write("         <h3 class=\"w3-padding-16 w3-text-light-grey\">Login & Sign Up</h3>\r\n");
      out.write("         <div class=\"w3-row-padding\" style=\"margin:0 -16px\">\r\n");
      out.write("            <div class=\"w3-half w3-margin-bottom\">\r\n");
      out.write("               <ul class=\"w3-ul w3-white w3-center w3-opacity w3-hover-opacity-off\">\r\n");
      out.write("                  <form method=\"POST\" action=");
      out.print(request.getContextPath() + "/signup");
      out.write(">\r\n");
      out.write("                     <li class=\"w3-dark-grey w3-xlarge w3-padding-16\">Sign Up</li>\r\n");
      out.write("                     <!-- When user signed up successfully -->\t\t\t\t  \r\n");
      out.write("                     ");
      if (_jspx_meth_c_005fif_005f0(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("                     <!-- When user fail to sign up -->\r\n");
      out.write("                     ");
      if (_jspx_meth_c_005fif_005f1(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("                     <input class=\"w3-input w3-padding-16\" placeholder=\"Enter your firstname\" name=\"firstname\" autocomplete=\"off\" type=\"text\">\r\n");
      out.write("                     <input class=\"w3-input w3-padding-16\" placeholder=\"Enter your lastname\" name=\"lastname\" autocomplete=\"off\" type=\"text\">\r\n");
      out.write("                     <input class=\"w3-input w3-padding-16\" placeholder=\"Enter your email\" name=\"email\" autocomplete=\"off\" type=\"text\">\r\n");
      out.write("                     <input class=\"w3-input w3-padding-16\" placeholder=\"Enter your password\" name=\"password\" type=\"password\">\r\n");
      out.write("                     <li class=\"w3-light-grey w3-padding-24\">\r\n");
      out.write("                        <button class=\"w3-button w3-white w3-padding-large w3-hover-black\">Sign Up</button>\r\n");
      out.write("                     </li>\r\n");
      out.write("                  </form>\r\n");
      out.write("               </ul>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"w3-half\">\r\n");
      out.write("               <ul class=\"w3-ul w3-white w3-center w3-opacity w3-hover-opacity-off\">\r\n");
      out.write("                  <form method=\"POST\" action=");
      out.print(request.getContextPath() + "/login");
      out.write(">\r\n");
      out.write("                     <li class=\"w3-dark-grey w3-xlarge w3-padding-16\">Login</li>\r\n");
      out.write("                     <!-- Check if user logged in successfully -->\t\t\t\t  \r\n");
      out.write("                     ");

				                       if (session != null && session.getAttribute("isLoggedIn") != null && session.getAttribute("isLoggedIn").equals(true)) {
				                       
      out.write("\r\n");
      out.write("                     <li class=\"w3-green w3-xlarge w3-padding-16\">You logged in successfully</li>\r\n");
      out.write("                     ");

                     } else if (session != null && session.getAttribute("isLoggedIn") != null && session.getAttribute("isLoggedIn").equals(false)) {
                     
      out.write("\r\n");
      out.write("                     <li class=\"w3-red w3-xlarge w3-padding-16\">Failed to login</li>\r\n");
      out.write("                     ");

                     }
                     
      out.write("\r\n");
      out.write("                     <p class=\"w3-left-align w3-block label-email\">Email</p>\r\n");
      out.write("                     <input class=\"w3-input w3-padding-16\" placeholder=\"Enter your email\" autocomplete=\"off\" type=\"text\" name=\"email\" >\r\n");
      out.write("                     <p class=\"w3-left-align w3-block label-password\">Password</p>\r\n");
      out.write("                     <input class=\"w3-input w3-padding-16\" placeholder=\"Enter your password\" type=\"password\" name=\"password\">\r\n");
      out.write("                     <li class=\"w1-padding-16\" style=\"text-align: left;margin: 7px;border: none;\">\r\n");
      out.write("                        <span class=\"w3-opacity\">Your info will be securitised</span>\r\n");
      out.write("                     </li>\r\n");
      out.write("                     <li class=\"w3-light-grey w3-padding-24\">\r\n");
      out.write("                        <button class=\"w3-button w3-white w3-padding-large w3-hover-black\" type=\"submit\">Login</button>\r\n");
      out.write("                     </li>\r\n");
      out.write("                  </form>\r\n");
      out.write("               </ul>\r\n");
      out.write("            </div>\r\n");
      out.write("         </div>\r\n");
      out.write("         <!-- Q/A Section -->\r\n");
      out.write("         <div class=\"w3-content\" id=\"q-a-page\">\r\n");
      out.write("            <h2 class=\"w3-text-light-grey\">Q/A Section</h2>\r\n");
      out.write("            <hr style=\"width:200px\" class=\"w3-opacity\">\r\n");
      out.write("            ");

            if (session.getAttribute("cantComment") != null && session.getAttribute("cantComment").equals(false)) {
            
      out.write("\r\n");
      out.write("            <li class=\"w3-red w3-padding-16\">You are not logged in</li>\r\n");
      out.write("            ");

            }
            
      out.write("\r\n");
      out.write("            ");

            if (session.getAttribute("isLoggedIn") != null && session.getAttribute("isLoggedIn").equals(true)) {
            
      out.write("\r\n");
      out.write("            <form action=\"");
      out.print(request.getContextPath() + "/comment");
      out.write("\" method=\"POST\" style=\"display: flex;flex-direction: row;align-items: flex-end;\">\r\n");
      out.write("               <input style=\"width: 70%;\" class=\"w3-input w3-padding-16\" name=\"commentContent\" placeholder=\"Write something\" autocomplete=\"off\" type=\"text\">\r\n");
      out.write("               <button style=\"width: 30%;height: 56px;\" class=\" w3-button w3-white w3-padding-large\" type=\"submit\">\r\n");
      out.write("               <i class=\"fa fa-paper-plane\" style=\"margin-right:14px\"></i>\r\n");
      out.write("               comment\r\n");
      out.write("               </button>\r\n");
      out.write("            </form>\r\n");
      out.write("            ");

            }
            
      out.write("\r\n");
      out.write("            <div class=\"q-a-page-content\">\r\n");
      out.write("               ");

               CommentDaoImpl commentDaoImpl = new CommentDaoImpl();
                                 	                  
                                 	                  List<Object[]> comments = commentDaoImpl.getAllComments();
                                                   
                                                   // check if there are some comments
                                                   if (comments.size() > 0) {
                                                   
                                 	                  for (Object[] comment : comments) { 
                                 	                  	String firstLetter = comment[4].toString().substring(0, 1).toUpperCase();
                                 	                  	String firstName = comment[4].toString();
                                 	                  	String lastName = comment[5].toString().toUpperCase();
                                 	                  	String commentContent = comment[2].toString();
                                 	                  	
                                 	                  	String CapitalizeFirstName = firstName.substring(0, 1).toUpperCase() + firstName.substring(1).toLowerCase();
                                 	                  	String CapitalizeLastName = lastName.substring(0, 1).toUpperCase() + lastName.substring(1).toLowerCase();
                                 	                	
                                 	                  	pageContext.setAttribute("commentContent", commentContent);
                                 	                  	pageContext.setAttribute("CapitalizeFirstName", CapitalizeFirstName);
                                 	                  	pageContext.setAttribute("CapitalizeLastName", CapitalizeLastName);
                                 	                  	pageContext.setAttribute("firstLetter", firstLetter);
               
      out.write("\r\n");
      out.write("               <div class=\"w3-panel w3-padding-16\">\r\n");
      out.write("                  <div class=\"name-container\">\r\n");
      out.write("                     <div class=\"circle\">\r\n");
      out.write("                        <span>\r\n");
      out.write("                           ");
      if (_jspx_meth_c_005fout_005f0(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("                        </span>\r\n");
      out.write("                     </div>\r\n");
      out.write("                     <div class=\"name\">\r\n");
      out.write("                        <span>\r\n");
      out.write("                           ");
      if (_jspx_meth_c_005fout_005f1(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("                        </span>\r\n");
      out.write("                     </div>\r\n");
      out.write("                  </div>\r\n");
      out.write("                  <p class=\"content\">\r\n");
      out.write("                     ");
      if (_jspx_meth_c_005fout_005f2(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("                  </p>\r\n");
      out.write("               </div>\r\n");
      out.write("               ");

               }
               
      out.write("\r\n");
      out.write("               ");

               } else {
               
      out.write("\r\n");
      out.write("               <div class=\"w3-dark-grey w3-panel w3-padding-16\" style=\"opacity: 0.5\">\r\n");
      out.write("                  <span>There are no comments right now</span>\r\n");
      out.write("               </div>\r\n");
      out.write("               ");

               }
               
      out.write("\r\n");
      out.write("            </div>\r\n");
      out.write("         </div>\r\n");
      out.write("         <!-- Appointment Section -->\r\n");
      out.write("         <div class=\"w3-padding-64 w3-content w3-text-grey\" id=\"ask-for-appointment\" style=\"margin-top: 200px\">\r\n");
      out.write("            <h2 class=\"w3-text-light-grey\">Appointment</h2>\r\n");
      out.write("            <hr style=\"width:200px\" class=\"w3-opacity\">\r\n");
      out.write("            ");

            if (session != null && session.getAttribute("isBooked") != null && session.getAttribute("isBooked").equals(true)) {
            
      out.write("\r\n");
      out.write("            <div class=\"w3-panel w3-green w3-padding-16\">\r\n");
      out.write("               Your appointment booked successfully\r\n");
      out.write("            </div>\r\n");
      out.write("            ");

            } else if (session != null && session.getAttribute("isBooked") != null && session.getAttribute("isBooked").equals(false) ) {
            
      out.write("\r\n");
      out.write("            <div class=\"w3-panel w3-red w3-padding-16\">\r\n");
      out.write("               You can't make an appointment\r\n");
      out.write("            </div>\r\n");
      out.write("            ");

            }
            
      out.write("\r\n");
      out.write("            <!-- Get next day: LocalDate.parse(\"2021-02-20\").plusDays(1).toString() -->\r\n");
      out.write("            <form action=\"");
      out.print(request.getContextPath() + "/appointment");
      out.write("\" method=\"POST\">\r\n");
      out.write("               <div class=\"w3-padding-16\" style=\"display:flex\">\r\n");
      out.write("                  <select class=\"w3-select w3-padding-16\" name=\"petsNumber\">\r\n");
      out.write("                     <option class=\"w3-padding-16\" value=\"default\" disabled selected>Number of pets</option>\r\n");
      out.write("                     <option class=\"w3-padding-16\" value=\"1\">1</option>\r\n");
      out.write("                     <option class=\"w3-padding-16\" value=\"2\">2</option>\r\n");
      out.write("                     <option class=\"w3-padding-16\" value=\"3\">3</option>\r\n");
      out.write("                     <option class=\"w3-padding-16\" value=\"4\">4</option>\r\n");
      out.write("                  </select>\r\n");
      out.write("                  <select class=\"w3-select w3-padding-16\" name=\"petType\">\r\n");
      out.write("                     <option class=\"w3-padding-16\" value=\"default\" disabled selected>Pet type</option>\r\n");
      out.write("                     <option class=\"w3-padding-16\" value=\"Dog\">Dog</option>\r\n");
      out.write("                     <option class=\"w3-padding-16\" value=\"Cat\">Cat</option>\r\n");
      out.write("                     <option class=\"w3-padding-16\" value=\"Rabbit\">Rabbit</option>\r\n");
      out.write("                     <option class=\"w3-padding-16\" value=\"Ferret\">Ferret</option>\r\n");
      out.write("                     <option class=\"w3-padding-16\" value=\"Hamster\">Hamster</option>\r\n");
      out.write("                     <option class=\"w3-padding-16\" value=\"Rat\">Rat</option>\r\n");
      out.write("                  </select>\r\n");
      out.write("               </div>\r\n");
      out.write("               <div class=\"w3-padding-16\" style=\"display:flex\">\r\n");
      out.write("                  <select class=\"w3-select w3-padding-16\" name=\"dateAppointment\">\r\n");
      out.write("                     <option class=\"w3-padding-16\" value=\"\" disabled selected>Choose date appointment</option>\r\n");
      out.write("                     ");

                     DateDaoImpl dateDaoImpl = new DateDaoImpl();
                      List<Date> dates = dateDaoImpl.getAllDates();
                      for (Date date : dates) {
                      	if (!date.isTaken()){
                     
      out.write("\r\n");
      out.write("                     <option class=\"w3-padding-16\" value=\"");
      out.print(date.getDate());
      out.write('"');
      out.write('>');
      out.write(' ');
      out.print(date.getDate());
      out.write(" </option>\r\n");
      out.write("                     ");
 } 
      out.write("\r\n");
      out.write("                     ");
 } 
      out.write("\r\n");
      out.write("                  </select>\r\n");
      out.write("                  <select class=\"w3-select w3-padding-16\" name=\"timeAppointment\">\r\n");
      out.write("                     <option class=\"w3-padding-16\" value=\"\" disabled selected>Choose time appointment</option>\r\n");
      out.write("                     ");

                     for (Date date : dates) { 
                       if (!date.isTaken()) {
                     
      out.write("\r\n");
      out.write("                     <option class=\"w3-padding-16\" value=\"");
      out.print( date.getTime() );
      out.write(';');
      out.print( date.getID() );
      out.write("\">\r\n");
      out.write("                     \t");
      out.print(  date.getTime() );
      out.write("\r\n");
      out.write("                     </option>\r\n");
      out.write("                     ");
 } 
      out.write("\r\n");
      out.write("            \r\n");
      out.write("                     ");
 } 
      out.write("\r\n");
      out.write("                  </select>\r\n");
      out.write("               </div>\r\n");
      out.write("               <button class=\"w3-margin-top w3-block w3-button w3-light-grey w3-padding-large\" type=\"submit\">\r\n");
      out.write("               CONFIRM APPOINTMENT\r\n");
      out.write("               </button>\r\n");
      out.write("            </form>\r\n");
      out.write("            <!-- End Appointment Section -->\r\n");
      out.write("         </div>\r\n");
      out.write("      </div>\r\n");
      out.write("   </body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_c_005fif_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:if
    org.apache.taglibs.standard.tag.el.core.IfTag _jspx_th_c_005fif_005f0 = (org.apache.taglibs.standard.tag.el.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.el.core.IfTag.class);
    boolean _jspx_th_c_005fif_005f0_reused = false;
    try {
      _jspx_th_c_005fif_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fif_005f0.setParent(null);
      // /index.jsp(90,21) name = test type = java.lang.String reqTime = false required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fif_005f0.setTest("${isUserSingedUp}");
      int _jspx_eval_c_005fif_005f0 = _jspx_th_c_005fif_005f0.doStartTag();
      if (_jspx_eval_c_005fif_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\r\n");
          out.write("                        <li class=\"w3-green w3-xlarge w3-padding-16\">You signed up successfully</li>\r\n");
          out.write("                     ");
          int evalDoAfterBody = _jspx_th_c_005fif_005f0.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fif_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f0);
      _jspx_th_c_005fif_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fif_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fif_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fif_005f1(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:if
    org.apache.taglibs.standard.tag.el.core.IfTag _jspx_th_c_005fif_005f1 = (org.apache.taglibs.standard.tag.el.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.el.core.IfTag.class);
    boolean _jspx_th_c_005fif_005f1_reused = false;
    try {
      _jspx_th_c_005fif_005f1.setPageContext(_jspx_page_context);
      _jspx_th_c_005fif_005f1.setParent(null);
      // /index.jsp(94,21) name = test type = java.lang.String reqTime = false required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fif_005f1.setTest("${!isUserSingedUp && isUserSingedUp != null}");
      int _jspx_eval_c_005fif_005f1 = _jspx_th_c_005fif_005f1.doStartTag();
      if (_jspx_eval_c_005fif_005f1 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\r\n");
          out.write("                        <li class=\"w3-red w3-xlarge w3-padding-16\">Failed to sign up</li>\r\n");
          out.write("                     ");
          int evalDoAfterBody = _jspx_th_c_005fif_005f1.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fif_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f1);
      _jspx_th_c_005fif_005f1_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fif_005f1, _jsp_getInstanceManager(), _jspx_th_c_005fif_005f1_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fout_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:out
    org.apache.taglibs.standard.tag.el.core.OutTag _jspx_th_c_005fout_005f0 = (org.apache.taglibs.standard.tag.el.core.OutTag) _005fjspx_005ftagPool_005fc_005fout_0026_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.el.core.OutTag.class);
    boolean _jspx_th_c_005fout_005f0_reused = false;
    try {
      _jspx_th_c_005fout_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fout_005f0.setParent(null);
      // /index.jsp(188,27) name = value type = java.lang.String reqTime = false required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fout_005f0.setValue("${firstLetter}");
      int _jspx_eval_c_005fout_005f0 = _jspx_th_c_005fout_005f0.doStartTag();
      if (_jspx_th_c_005fout_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fout_0026_005fvalue_005fnobody.reuse(_jspx_th_c_005fout_005f0);
      _jspx_th_c_005fout_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fout_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fout_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fout_005f1(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:out
    org.apache.taglibs.standard.tag.el.core.OutTag _jspx_th_c_005fout_005f1 = (org.apache.taglibs.standard.tag.el.core.OutTag) _005fjspx_005ftagPool_005fc_005fout_0026_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.el.core.OutTag.class);
    boolean _jspx_th_c_005fout_005f1_reused = false;
    try {
      _jspx_th_c_005fout_005f1.setPageContext(_jspx_page_context);
      _jspx_th_c_005fout_005f1.setParent(null);
      // /index.jsp(193,27) name = value type = java.lang.String reqTime = false required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fout_005f1.setValue("${CapitalizeFirstName} ${CapitalizeLastName}");
      int _jspx_eval_c_005fout_005f1 = _jspx_th_c_005fout_005f1.doStartTag();
      if (_jspx_th_c_005fout_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fout_0026_005fvalue_005fnobody.reuse(_jspx_th_c_005fout_005f1);
      _jspx_th_c_005fout_005f1_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fout_005f1, _jsp_getInstanceManager(), _jspx_th_c_005fout_005f1_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fout_005f2(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:out
    org.apache.taglibs.standard.tag.el.core.OutTag _jspx_th_c_005fout_005f2 = (org.apache.taglibs.standard.tag.el.core.OutTag) _005fjspx_005ftagPool_005fc_005fout_0026_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.el.core.OutTag.class);
    boolean _jspx_th_c_005fout_005f2_reused = false;
    try {
      _jspx_th_c_005fout_005f2.setPageContext(_jspx_page_context);
      _jspx_th_c_005fout_005f2.setParent(null);
      // /index.jsp(198,21) name = value type = java.lang.String reqTime = false required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fout_005f2.setValue("${commentContent}");
      int _jspx_eval_c_005fout_005f2 = _jspx_th_c_005fout_005f2.doStartTag();
      if (_jspx_th_c_005fout_005f2.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fout_0026_005fvalue_005fnobody.reuse(_jspx_th_c_005fout_005f2);
      _jspx_th_c_005fout_005f2_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fout_005f2, _jsp_getInstanceManager(), _jspx_th_c_005fout_005f2_reused);
    }
    return false;
  }
}
